/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
module.exports = fibonacciSequence;

function fibonacciSequence() {
    var sum = 2;
    var range = [1, 2];
    function evenSequence(){
        var num = range[0]+range[1];
        while (num < 4000000){
            if (num % 2 === 0){
                sum += num;
            }
            range.shift();
            range.push(num);
            num = range[0] + range[1];
        }
    }
    evenSequence();
    return sum;
}

fibonacciSequence();
